import type { Question } from './types'

type Bank = Record<string, Question[]>

export const QUESTION_BANK: Bank = {
  'General Knowledge': [
    { q: 'What is the capital of France?', choices: ['Berlin', 'Madrid', 'Paris', 'Rome'], answer: 2 },
    { q: 'What planet is known as the Red Planet?', choices: ['Venus', 'Mars', 'Jupiter', 'Saturn'], answer: 1 },
    { q: 'How many continents are there?', choices: ['5', '6', '7', '8'], answer: 2 },
    { q: 'What is H2O?', choices: ['Salt', 'Water', 'Oxygen', 'Gold'], answer: 1 },
    { q: 'Largest ocean on Earth?', choices: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answer: 3 },
    { q: 'How many sides does a hexagon have?', choices: ['5', '6', '7', '8'], answer: 1 },
    { q: 'What color do you get mixing red and blue?', choices: ['Green', 'Purple', 'Orange', 'Brown'], answer: 1 },
    { q: 'Who painted the Mona Lisa?', choices: ['Van Gogh', 'Picasso', 'Da Vinci', 'Monet'], answer: 2 },
    { q: 'Tallest mountain in the world?', choices: ['K2', 'Everest', 'Denali', 'Kilimanjaro'], answer: 1 },
    { q: 'How many bones in the human body?', choices: ['206', '210', '195', '220'], answer: 0 },
    { q: 'Currency of Japan?', choices: ['Won', 'Yuan', 'Yen', 'Ringgit'], answer: 2 },
    { q: 'Author of Harry Potter?', choices: ['Tolkien', 'Rowling', 'Martin', 'King'], answer: 1 },
    { q: 'How many minutes in a day?', choices: ['1200', '1440', '1600', '2400'], answer: 1 },
    { q: 'Fastest land animal?', choices: ['Lion', 'Horse', 'Cheetah', 'Gazelle'], answer: 2 },
    { q: 'Smallest prime number?', choices: ['0', '1', '2', '3'], answer: 2 },
    { q: 'Square root of 144?', choices: ['10', '11', '12', '13'], answer: 2 },
    { q: 'What does CPU stand for?', choices: ['Central Process Unit', 'Central Processing Unit', 'Core Power Unit', 'Computer Power Unit'], answer: 1 },
    { q: 'Year WWII ended?', choices: ['1943', '1944', '1945', '1946'], answer: 2 },
    { q: 'Hottest planet in our solar system?', choices: ['Mercury', 'Venus', 'Mars', 'Jupiter'], answer: 1 },
    { q: 'Hardest natural substance?', choices: ['Iron', 'Diamond', 'Quartz', 'Gold'], answer: 1 },
    { q: 'How many players on a soccer team?', choices: ['9', '10', '11', '12'], answer: 2 },
    { q: 'Largest mammal?', choices: ['Elephant', 'Blue Whale', 'Giraffe', 'Hippo'], answer: 1 },
    { q: 'Number of strings on a guitar (standard)?', choices: ['4', '5', '6', '7'], answer: 2 },
    { q: 'What gas do plants absorb?', choices: ['Oxygen', 'Nitrogen', 'CO2', 'Helium'], answer: 2 },
    { q: 'Chemical symbol for gold?', choices: ['Go', 'Gd', 'Au', 'Ag'], answer: 2 },
    { q: 'How many degrees in a right angle?', choices: ['45', '90', '180', '360'], answer: 1 },
    { q: 'Largest desert in the world?', choices: ['Sahara', 'Gobi', 'Antarctic', 'Arabian'], answer: 2 },
    { q: 'What language has the most native speakers?', choices: ['English', 'Spanish', 'Mandarin', 'Hindi'], answer: 2 },
    { q: 'Number of weeks in a year?', choices: ['50', '52', '54', '48'], answer: 1 },
    { q: 'How many teeth do adult humans have?', choices: ['28', '30', '32', '34'], answer: 2 },
  ],
  'Tech & Hacking': [
    { q: 'What does HTML stand for?', choices: ['Hyper Trainer Markup Language', 'HyperText Markup Language', 'HighText Machine Language', 'HyperText Marking Language'], answer: 1 },
    { q: 'Port number for HTTPS?', choices: ['80', '443', '8080', '22'], answer: 1 },
    { q: 'Who founded Microsoft?', choices: ['Jobs', 'Gates', 'Musk', 'Page'], answer: 1 },
    { q: '"DDoS" stands for?', choices: ['Distributed Denial of Service', 'Direct Denial of System', 'Data Driven Online Service', 'Domain Denial of Server'], answer: 0 },
    { q: 'A common SQL injection symbol?', choices: ['#', '\'', '$', '%'], answer: 1 },
    { q: 'What hash is 32 hex chars long?', choices: ['SHA-1', 'MD5', 'SHA-256', 'bcrypt'], answer: 1 },
    { q: 'What does VPN stand for?', choices: ['Virtual Private Network', 'Verified Public Network', 'Visual Process Node', 'Variable Packet Number'], answer: 0 },
    { q: 'Default SSH port?', choices: ['21', '22', '23', '25'], answer: 1 },
    { q: 'Which is NOT a programming language?', choices: ['Python', 'HTML', 'Rust', 'Go'], answer: 1 },
    { q: 'Linus Torvalds created?', choices: ['Windows', 'macOS', 'Linux', 'Android'], answer: 2 },
    { q: 'Binary 1010 in decimal?', choices: ['8', '9', '10', '11'], answer: 2 },
    { q: 'What encoding turns binary into text?', choices: ['ASCII', 'Base64', 'UTF-32', 'Hex'], answer: 1 },
    { q: 'Acronym "API" stands for?', choices: ['Application Programming Interface', 'Applied Program Index', 'Async Process Indicator', 'Auto Page Insert'], answer: 0 },
    { q: 'What does "ping" measure?', choices: ['Bandwidth', 'Latency', 'Storage', 'Power'], answer: 1 },
    { q: 'A "0day" is?', choices: ['Free trial', 'Unknown exploit', 'Domain reset', 'IP refresh'], answer: 1 },
    { q: '"Phishing" attacks target?', choices: ['Routers', 'Humans', 'CPUs', 'Cables'], answer: 1 },
    { q: 'Bitcoin was created in?', choices: ['2005', '2009', '2013', '2015'], answer: 1 },
    { q: 'Which is a NoSQL database?', choices: ['MySQL', 'Postgres', 'MongoDB', 'SQLite'], answer: 2 },
    { q: 'What does "RAM" stand for?', choices: ['Random Access Memory', 'Read Access Memory', 'Run All Memory', 'Rapid Action Module'], answer: 0 },
    { q: 'JavaScript was created in?', choices: ['1991', '1995', '2000', '2005'], answer: 1 },
    { q: 'Common encryption algorithm?', choices: ['JPEG', 'AES', 'MP3', 'HTML'], answer: 1 },
    { q: 'IPv4 address has how many octets?', choices: ['2', '3', '4', '6'], answer: 2 },
    { q: '"Cookie" stores data where?', choices: ['Server only', 'Browser', 'CPU', 'GPU'], answer: 1 },
    { q: 'What is "git"?', choices: ['Game engine', 'Version control', 'Database', 'Browser'], answer: 1 },
    { q: 'A "kernel" is part of?', choices: ['Network card', 'OS', 'Monitor', 'GPU'], answer: 1 },
    { q: 'Common SSL handshake step?', choices: ['Heartbeat', 'Client Hello', 'NAT punch', 'Ping flood'], answer: 1 },
    { q: 'CSS stands for?', choices: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style Syntax', 'Coded Style System'], answer: 1 },
    { q: 'What does "DNS" do?', choices: ['Encrypts files', 'Maps names to IPs', 'Stores data', 'Renders pages'], answer: 1 },
    { q: '"Brute force" tries?', choices: ['One password', 'Many passwords', 'Social engineering', 'Phishing email'], answer: 1 },
    { q: 'A "MITM" attack is?', choices: ['Man In The Middle', 'Modify Internal Memory', 'Multi-Instance Threat Model', 'Main Internet Tunnel Mode'], answer: 0 },
  ],
  'Pop Culture': [
    { q: 'Which superhero is also Bruce Wayne?', choices: ['Superman', 'Spider-Man', 'Batman', 'Iron Man'], answer: 2 },
    { q: 'Lead singer of Queen?', choices: ['Bowie', 'Mercury', 'Jagger', 'Plant'], answer: 1 },
    { q: 'The Matrix red or blue pill?', choices: ['Yellow', 'Green', 'Red/Blue', 'Pink'], answer: 2 },
    { q: 'Studio behind Frozen?', choices: ['Pixar', 'Disney', 'DreamWorks', 'Illumination'], answer: 1 },
    { q: 'Which is NOT a Marvel character?', choices: ['Thor', 'Joker', 'Hulk', 'Loki'], answer: 1 },
    { q: '"To infinity and ___"?', choices: ['back', 'beyond', 'above', 'forever'], answer: 1 },
    { q: 'Pokémon\'s yellow electric mascot?', choices: ['Charmander', 'Squirtle', 'Pikachu', 'Bulbasaur'], answer: 2 },
    { q: 'Author of Game of Thrones?', choices: ['Tolkien', 'Sanderson', 'Martin', 'King'], answer: 2 },
    { q: 'Year Minecraft released?', choices: ['2009', '2011', '2013', '2015'], answer: 1 },
    { q: 'Fortnite developer?', choices: ['EA', 'Epic', 'Valve', 'Activision'], answer: 1 },
    { q: 'Mario\'s brother?', choices: ['Wario', 'Luigi', 'Toad', 'Yoshi'], answer: 1 },
    { q: '"Wakanda Forever" is from?', choices: ['Spider-Man', 'Black Panther', 'Iron Man', 'Doctor Strange'], answer: 1 },
    { q: 'Number of Harry Potter books?', choices: ['6', '7', '8', '9'], answer: 1 },
    { q: 'TikTok is owned by?', choices: ['Meta', 'ByteDance', 'Google', 'Tencent'], answer: 1 },
    { q: 'Who hosts SpaceX?', choices: ['Bezos', 'Musk', 'Branson', 'Gates'], answer: 1 },
    { q: '"May the force be with you" is from?', choices: ['Star Trek', 'Star Wars', 'Marvel', 'Avatar'], answer: 1 },
    { q: 'Spotify is from?', choices: ['Sweden', 'USA', 'UK', 'Germany'], answer: 0 },
    { q: 'Among Us color most sus?', choices: ['Blue', 'Red', 'Yellow', 'Green'], answer: 1 },
    { q: 'Minecraft\'s scary night enemy?', choices: ['Goomba', 'Creeper', 'Slime', 'Ender'], answer: 1 },
    { q: 'Roblox launched in?', choices: ['2002', '2006', '2010', '2014'], answer: 1 },
    { q: 'Which artist sang "Anti-Hero"?', choices: ['Adele', 'Beyoncé', 'Taylor Swift', 'Billie'], answer: 2 },
    { q: 'Studio behind Spider-Verse?', choices: ['Pixar', 'Sony', 'Disney', 'Warner'], answer: 1 },
    { q: 'Stranger Things is on?', choices: ['Hulu', 'Netflix', 'Disney+', 'HBO'], answer: 1 },
    { q: 'Iron Man\'s AI?', choices: ['HAL', 'JARVIS', 'CORTANA', 'SIRI'], answer: 1 },
    { q: 'Disney mascot?', choices: ['Donald', 'Goofy', 'Mickey', 'Pluto'], answer: 2 },
    { q: 'Game with a battle royale on an island?', choices: ['Minecraft', 'Fortnite', 'Roblox', 'Terraria'], answer: 1 },
    { q: 'Voice of Shrek?', choices: ['Pitt', 'Myers', 'Smith', 'Damon'], answer: 1 },
    { q: '"Hakuna Matata" is from?', choices: ['Aladdin', 'Lion King', 'Moana', 'Tarzan'], answer: 1 },
    { q: 'Pixar lamp\'s name?', choices: ['Lumi', 'Luxo Jr.', 'Pixie', 'Spark'], answer: 1 },
    { q: 'YouTube launched in?', choices: ['2003', '2005', '2007', '2009'], answer: 1 },
  ],
  'Math': [
    { q: '7 × 8?', choices: ['54', '56', '58', '64'], answer: 1 },
    { q: '15 + 27?', choices: ['41', '42', '43', '44'], answer: 1 },
    { q: '100 ÷ 4?', choices: ['20', '25', '30', '40'], answer: 1 },
    { q: '12²?', choices: ['124', '144', '154', '164'], answer: 1 },
    { q: '√81?', choices: ['7', '8', '9', '10'], answer: 2 },
    { q: '3⁴?', choices: ['27', '64', '81', '243'], answer: 2 },
    { q: '50% of 240?', choices: ['100', '110', '120', '130'], answer: 2 },
    { q: '8! equals?', choices: ['40320', '5040', '362880', '20160'], answer: 0 },
    { q: '2 + 2 × 2?', choices: ['6', '8', '4', '10'], answer: 0 },
    { q: 'Sum of angles in a triangle?', choices: ['90°', '180°', '270°', '360°'], answer: 1 },
    { q: 'Pi to 2 decimals?', choices: ['3.12', '3.14', '3.16', '3.18'], answer: 1 },
    { q: '0.5 + 0.25?', choices: ['0.7', '0.75', '0.8', '1'], answer: 1 },
    { q: '1000 - 367?', choices: ['623', '633', '643', '653'], answer: 1 },
    { q: '9 × 9?', choices: ['72', '81', '90', '99'], answer: 1 },
    { q: '17 + 25?', choices: ['40', '41', '42', '43'], answer: 2 },
    { q: 'Prime: which?', choices: ['9', '15', '17', '21'], answer: 2 },
    { q: '64 ÷ 8?', choices: ['6', '7', '8', '9'], answer: 2 },
    { q: '5³?', choices: ['25', '75', '125', '225'], answer: 2 },
    { q: '20% of 150?', choices: ['25', '30', '35', '40'], answer: 1 },
    { q: 'Half of 88?', choices: ['42', '44', '46', '48'], answer: 1 },
    { q: 'Next prime after 7?', choices: ['9', '11', '13', '15'], answer: 1 },
    { q: '11 × 12?', choices: ['122', '132', '142', '144'], answer: 1 },
    { q: 'Roman numeral L?', choices: ['5', '50', '100', '500'], answer: 1 },
    { q: '15 × 6?', choices: ['80', '85', '90', '95'], answer: 2 },
    { q: '√225?', choices: ['12', '13', '14', '15'], answer: 3 },
    { q: '7² + 1?', choices: ['48', '49', '50', '51'], answer: 2 },
    { q: '40% of 200?', choices: ['60', '70', '80', '90'], answer: 2 },
    { q: '999 + 1?', choices: ['999', '1000', '1001', '1010'], answer: 1 },
    { q: '4! equals?', choices: ['16', '20', '24', '32'], answer: 2 },
    { q: '6 + 5 × 2?', choices: ['16', '22', '11', '13'], answer: 0 },
  ],
  'Science': [
    { q: 'Speed of light (approx)?', choices: ['300k km/s', '150k km/s', '600k km/s', '900k km/s'], answer: 0 },
    { q: 'Symbol for sodium?', choices: ['So', 'Na', 'S', 'Sn'], answer: 1 },
    { q: 'Closest star to Earth?', choices: ['Proxima Centauri', 'Sun', 'Sirius', 'Alpha Centauri'], answer: 1 },
    { q: 'How many bones in adult human?', choices: ['200', '206', '212', '220'], answer: 1 },
    { q: 'Element with atomic # 1?', choices: ['Helium', 'Hydrogen', 'Oxygen', 'Lithium'], answer: 1 },
    { q: 'pH of pure water?', choices: ['5', '6', '7', '8'], answer: 2 },
    { q: 'Largest organ in human body?', choices: ['Liver', 'Skin', 'Heart', 'Brain'], answer: 1 },
    { q: 'Bees produce?', choices: ['Silk', 'Honey', 'Milk', 'Wax only'], answer: 1 },
    { q: 'A "light-year" measures?', choices: ['Time', 'Distance', 'Speed', 'Weight'], answer: 1 },
    { q: 'Most abundant gas in atmosphere?', choices: ['Oxygen', 'Nitrogen', 'CO2', 'Argon'], answer: 1 },
    { q: 'Newton\'s laws are about?', choices: ['Heat', 'Motion', 'Light', 'Sound'], answer: 1 },
    { q: 'DNA shape?', choices: ['Cube', 'Helix', 'Square', 'Triangle'], answer: 1 },
    { q: 'Earth\'s age (approx)?', choices: ['1B yrs', '2.5B yrs', '4.5B yrs', '8B yrs'], answer: 2 },
    { q: 'Tectonic plates exist on?', choices: ['Mars', 'Moon', 'Earth', 'Sun'], answer: 2 },
    { q: 'Photosynthesis uses?', choices: ['Sunlight', 'Moonlight', 'Heat', 'Sound'], answer: 0 },
    { q: 'Largest planet?', choices: ['Saturn', 'Jupiter', 'Neptune', 'Uranus'], answer: 1 },
    { q: 'Force keeping us on Earth?', choices: ['Magnetism', 'Gravity', 'Friction', 'Pressure'], answer: 1 },
    { q: 'Animal with longest neck?', choices: ['Ostrich', 'Camel', 'Giraffe', 'Elephant'], answer: 2 },
    { q: 'Boiling point of water (°C)?', choices: ['90', '100', '110', '120'], answer: 1 },
    { q: 'Freezing point of water (°F)?', choices: ['0', '16', '32', '100'], answer: 2 },
    { q: 'Closest planet to Sun?', choices: ['Venus', 'Earth', 'Mercury', 'Mars'], answer: 2 },
    { q: 'Element O?', choices: ['Osmium', 'Oxygen', 'Olive', 'Ozone'], answer: 1 },
    { q: 'How many chambers in a human heart?', choices: ['2', '3', '4', '5'], answer: 2 },
    { q: 'Studies stars?', choices: ['Geology', 'Astronomy', 'Biology', 'Chemistry'], answer: 1 },
    { q: 'Tallest tree species?', choices: ['Oak', 'Pine', 'Redwood', 'Maple'], answer: 2 },
    { q: 'Sound travels fastest in?', choices: ['Air', 'Water', 'Steel', 'Vacuum'], answer: 2 },
    { q: 'Symbol for iron?', choices: ['Ir', 'In', 'Fe', 'I'], answer: 2 },
    { q: 'Cells without nucleus called?', choices: ['Eukaryotic', 'Prokaryotic', 'Plant', 'Animal'], answer: 1 },
    { q: 'Sun is a?', choices: ['Planet', 'Star', 'Comet', 'Moon'], answer: 1 },
    { q: 'A "joule" measures?', choices: ['Distance', 'Time', 'Energy', 'Mass'], answer: 2 },
  ],
}

export const CATEGORIES = Object.keys(QUESTION_BANK)
